# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\x1a\n\x07Payload\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x15\n\x04Ping\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"C\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t2S\n\x11\x43\x61lculatorService\x12\"\n\x0bSendRequest\x12\x08.Payload\x1a\x07.Result\"\x00\x12\x1a\n\x08SendPing\x12\x05.Ping\x1a\x05.Ping\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOAD']._serialized_start=20
  _globals['_PAYLOAD']._serialized_end=46
  _globals['_PING']._serialized_start=48
  _globals['_PING']._serialized_end=69
  _globals['_RESULT']._serialized_start=71
  _globals['_RESULT']._serialized_end=138
  _globals['_CALCULATORSERVICE']._serialized_start=140
  _globals['_CALCULATORSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
